# -*- coding: utf-8 -*-
"""finalprj.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1XyH6HjaiBGRpMDEiuZYztEB6L2a2GcGI
"""

# !pip install youtube_transcript_api  # Remove for deployment


from youtube_transcript_api import YouTubeTranscriptApi

import re

def get_video_id(url_link):
    match = re.search(r"(?:v=|be/)([a-zA-Z0-9_-]{11})", url_link)
    return match.group(1) if match else None

# Using the get_video_id function defined in cell Z4MmFsSTqLWC
a = get_video_id("https://youtu.be/r6zFZQm0hcc?si=bUTQONqUKBE_7T3D")
print(a)

dir(YouTubeTranscriptApi)

api=YouTubeTranscriptApi()
prj = api.fetch(a)
prj

prj_join="".join([line.text for line in prj])
prj_join



from deepmultilingualpunctuation import PunctuationModel

model = PunctuationModel()
text = prj_join
restored = model.restore_punctuation(text)
print(restored)

from transformers import pipeline
summarizer = pipeline("summarization", model="sshleifer/distilbart-cnn-12-6")
summary = summarizer(restored, max_length=120, min_length=30, do_sample=False)
print(summary[0]['summary_text'])

!pip install keybert

from keybert import KeyBERT
kw_model = KeyBERT()
keywords = kw_model.extract_keywords(restored, keyphrase_ngram_range=(1, 2), stop_words='english')
print(keywords)

